// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8hFB0L_dtPvqyqlnJ3k9DhXiVRbdawAE',
    appId: '1:929456343474:android:8c023d5165b93caae43cab',
    messagingSenderId: '929456343474',
    projectId: 'todo-ad842',
    storageBucket: 'todo-ad842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_pZflqnRLEVVgiPIeqWLBmsn8-55CbDE',
    appId: '1:929456343474:ios:0a120bec76fb2ea1e43cab',
    messagingSenderId: '929456343474',
    projectId: 'todo-ad842',
    storageBucket: 'todo-ad842.appspot.com',
    androidClientId: '929456343474-hli3bf47qv5hn0i0n5gicsuijs7lhnck.apps.googleusercontent.com',
    iosClientId: '929456343474-kvec089pc9hi93gr3ree7prvhkip4aea.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
